# Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).
{ config, pkgs, lib, ... }:
let
  owner = "lc";
in
{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  ##### Basic Info #####

  #usageScenario = "desktop";
  #tuning.level = 0;
  #wanInterfaces = [ "eno1" "wlp4s0" ];

  #boot.tmp.tmpfsSize = "1000%"; #构建大型项目需要，以物理内存为100%，不要大于物理内存加swap就好


  ##### About Boot #####

  boot.loader.grub = {
    enable = lib.mkDefault true;
    #useOSProber = true;
    device = "nodev";
    efiSupport = true;
    efiInstallAsRemovable = true;
  };
  #boot.loader.efi.canTouchEfiVariables = true;
  #boot.supportedFilesystems = [ "ntfs" ];

  ##### About Users #####

  users.users.${owner} = {
    isNormalUser = true;
    extraGroups = [
      "wheel" # Enable ‘sudo’ for the user.
    ];
    #shell = pkgs.zsh;
    # generated by: $  nix-shell -p mkpasswd --command "mkpasswd -m sha-512"
    hashedPassword = "";

    openssh.authorizedKeys.keys = [
      ""
    ];
  };

  users.users.root.openssh.authorizedKeys.keys = config.users.users.${owner}.openssh.authorizedKeys.keys;
  users.users.root.hashedPassword = config.users.users.${owner}.hashedPassword;

  security.sudo.extraRules = [
    {
      users = [ owner ];
      commands = [ { command = "ALL"; options = [ "SETENV" /* "NOPASSWD" */ ]; } ];
    }
  ];


  ##### About Nix & Nixpkgs #####

  nixpkgs.config.allowUnfree = true;

  nix = {
    #package = pkgs.nixVersions.latest; # NOTE: make sure nix-fast-build use same version
    extraOptions = ''
      experimental-features = nix-command flakes
      '';
  };

  #NOTE: use `--option substituters <url>` to apply immediately
        # e.g. `sudo nixos-install --option substituters https://mirror.sjtu.edu.cn/nix-channels/store`
  #nix.binaryCaches = lib.mkBefore [
  nix.settings.substituters = lib.mkBefore [
    "https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store"
    "https://mirror.sjtu.edu.cn/nix-channels/store"
    #"https://mirrors.bfsu.edu.cn/nix-channels/store"
  ];

  ##### About Network #####

  #networking.hostName = "bootstrap-nixos"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.
  #networking.interfaces.enp2s0.useDHCP = true;

  ##### About GUI #####

  # Enable the X11 windowing system.
  services.xserver.enable = true;


  # Enable the Plasma 5 Desktop Environment.
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.desktopManager.plasma5.enable = true;


  ##### About Softwares #####

  programs.chromium.enable = true;

  environment.systemPackages = with pkgs; [
  # sys tool
    wget
    neovim xclip
    git git-crypt gnupg pinentry-qt
    icdiff # 文本diff
    zsh antigen fzf sqlite
    ripgrep # rg 文本搜索，grep / ag 的替代品
    fd # 文件名搜索
    tldr # man / cheat 的替代品
    file # 查看文件信息
    tree # 树状展示文件目录结构
    mtr # 网络诊断工具 my traceroute
    #ntfs3g # 微软NTFS文件系统支持
    #proxychains

  # gui sys tool
    gpa #pgp密钥管理
    gparted #可视化分区工具
    #mtr-gui # 网络诊断工具 my traceroute GUI
    hardinfo # show hardware informations 查看系统硬件信息

  # required gui software
    #google-chrome
    chromium
    #firefox

  # daily gui software
    kdePackages.spectacle
    #crow-translate #翻译，带OCR功能
    telegram-desktop # the telegram desktop client
  ];

  environment.interactiveShellInit = ''
    alias vi=nvim
  '';

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  #system.stateVersion = "22.05";
}
